# Generated by Django 6.0.2 on 2026-02-26 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myportfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(upload_to='portfolio_project/'),
        ),
    ]
